module.exports = {
  users: {
    uid: 'string',
    email: 'string',
    name: 'string',
    role: 'customer|admin',
    createdAt: 'timestamp',
    updatedAt: 'timestamp',
  },
  admins: {
    uid: 'string',
    email: 'string',
    permissions: ['products', 'orders', 'analytics'],
    active: 'boolean',
  },
  products: {
    productId: 'string',
    name: 'string',
    category: 'string',
    subcategory: 'string',
    price: 'number',
    oldPrice: 'number',
    discountPercentage: 'number',
    rating: 'number',
    reviewCount: 'number',
    stock: 'number',
    sku: 'string',
    description: 'string',
    specifications: 'map',
    material: 'string',
    size: 'string',
    color: 'string',
    deliveryInfo: 'string',
    returnPolicy: 'string',
    warranty: 'string',
    sourceUrl: 'string',
    thumbnail: 'string',
    galleryImages: ['string'],
    isFeatured: 'boolean',
    isTrending: 'boolean',
    isBestSeller: 'boolean',
    createdAt: 'timestamp',
    updatedAt: 'timestamp',
  },
  categories: { categoryId: 'string', name: 'string', subtitle: 'string', imageUrl: 'string', productCount: 'number' },
  carts: { userId: 'string', items: [{ productId: 'string', quantity: 'number', price: 'number' }] },
  wishlists: { userId: 'string', productIds: ['string'] },
  orders: { orderId: 'string', userId: 'string', status: 'string', paymentStatus: 'string', total: 'number', addressId: 'string' },
  order_items: { orderItemId: 'string', orderId: 'string', productId: 'string', quantity: 'number', price: 'number' },
  addresses: { addressId: 'string', userId: 'string', name: 'string', phone: 'string', line1: 'string', city: 'string', pincode: 'string' },
  payments: { paymentId: 'string', orderId: 'string', razorpayOrderId: 'string', razorpayPaymentId: 'string', status: 'string', amount: 'number' },
  reviews: { reviewId: 'string', userId: 'string', productId: 'string', rating: 'number', comment: 'string' },
  notifications: { notificationId: 'string', userId: 'string', title: 'string', body: 'string', read: 'boolean' },
  chatbot_messages: { messageId: 'string', userId: 'string', text: 'string', isUser: 'boolean', recommendedProductIds: ['string'] },
  coupons: { code: 'string', discountPercent: 'number', minimumAmount: 'number', isActive: 'boolean' },
  banners: { bannerId: 'string', title: 'string', subtitle: 'string', imageUrl: 'string', isActive: 'boolean' },
  inventory: { productId: 'string', stock: 'number', lowStockThreshold: 'number', lastRestockedAt: 'timestamp' },
  returns: { returnId: 'string', orderId: 'string', userId: 'string', reason: 'string', status: 'string' },
  support_tickets: { ticketId: 'string', userId: 'string', subject: 'string', message: 'string', status: 'open|closed' },
};
